import {
  LayoutDashboard, Users, ShieldCheck, Package,
  FolderTree, TrendingUp, Settings, FolderOpen,
  Layers, Tag, LayoutGrid, Star, Unlock, List,
  ShoppingCart, MessageCircle, Info, CalendarDays,
  HelpCircle, Image, Award, Briefcase, Handshake,
  GraduationCap, Headphones,
} from "lucide-react";

export const sidebarMenuItems = [
  { id: "dashboard", labelKey: "sidebar.dashboard", icon: LayoutDashboard, href: "/dashboard" },
  { id: "users-sellers", labelKey: "sidebar.usersSellers", icon: Users, href: "/users-sellers" },
  { id: "verifications", labelKey: "sidebar.verifications", icon: ShieldCheck, href: "/verifications" },
  { id: "products", labelKey: "sidebar.products", icon: Package, href: "/products" },
  {
    id: "categories",
    labelKey: "sidebar.categories",
    icon: FolderTree,
    href: "/categories",
    submenu: [
      { id: "categories-all", labelKey: "sidebar.allCategories", icon: FolderOpen, href: "/categories" },
      { id: "categories-sub", labelKey: "sidebar.subCategories", icon: Layers, href: "/categories/sub-categories" },
      { id: "categories-product-types", labelKey: "sidebar.productTypes", icon: Tag, href: "/categories/product-types" },
    ],
  },
  { id: "sections", labelKey: "sidebar.sectionManagement", icon: LayoutGrid, href: "/sections" },
  { id: "banners", labelKey: "sidebar.banners", icon: Image, href: "/banners" },
  { id: "reviews", labelKey: "sidebar.reviews", icon: Star, href: "/reviews" },
  {
    id: "trade-leads",
    labelKey: "sidebar.tradeLeads",
    icon: TrendingUp,
    href: "/trade-leads",
    submenu: [
      { id: "trade-leads-all", labelKey: "sidebar.allTradeLeads", icon: List, href: "/trade-leads" },
      { id: "trade-leads-unlock", labelKey: "sidebar.unlockRequests", icon: Unlock, href: "/trade-leads/unlock-requests" },
    ],
  },
  { id: "trade-shows", labelKey: "sidebar.tradeShows", icon: CalendarDays, href: "/trade-shows" },
  { id: "investments", labelKey: "sidebar.investments", icon: Briefcase, href: "/investments" },
  { id: "partners", labelKey: "sidebar.partners", icon: Handshake, href: "/partners" },
  { id: "consultancy", labelKey: "sidebar.consultancy", icon: GraduationCap, href: "/consultancy" },
  { id: "support-chat", labelKey: "sidebar.supportChat", icon: Headphones, href: "/support-chat" },
  { id: "success-stories", labelKey: "sidebar.successStories", icon: Award, href: "/success-stories" },
  { id: "orders", labelKey: "sidebar.orders", icon: ShoppingCart, href: "/orders" },
  { id: "contact-us", labelKey: "sidebar.contactMessages", icon: MessageCircle, href: "/contact-us" },
  { id: "help-center", labelKey: "sidebar.helpCenter", icon: HelpCircle, href: "/help-center" },
  { id: "about", labelKey: "sidebar.aboutManagement", icon: Info, href: "/about" },
  { id: "settings", labelKey: "sidebar.settings", icon: Settings, href: "/settings" },
];