import {
  LayoutDashboard,
  Users,
  ShieldCheck,
  Package,
  FolderTree,
  TrendingUp,
  Wallet,
  PiggyBank,
  MessageSquare,
  Megaphone,
  AlertTriangle,
  Settings,
} from "lucide-react";

export const sidebarMenuItems = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: LayoutDashboard,
    href: "/dashboard",
  },
  {
    id: "users-sellers",
    label: "Users & Sellers",
    icon: Users,
    href: "/users-sellers",
    submenu: [
      { id: "all-users", label: "All Users", href: "/users-sellers" },
      { id: "buyers", label: "Buyers", href: "/users-sellers/buyers" },
      { id: "sellers", label: "Sellers", href: "/users-sellers/sellers" },
      { id: "admins", label: "Admins", href: "/users-sellers/admins" },
    ],
  },
  {
    id: "verifications",
    label: "Verifications",
    icon: ShieldCheck,
    href: "/verifications",
    submenu: [
      { id: "all-verifications", label: "All", href: "/verifications" },
      { id: "pending", label: "Pending", href: "/verifications/pending" },
      { id: "approved", label: "Approved", href: "/verifications/approved" },
      { id: "rejected", label: "Rejected", href: "/verifications/rejected" },
    ],
  },
  {
    id: "products",
    label: "Products",
    icon: Package,
    href: "/products",
    submenu: [
      { id: "all-products", label: "All Products", href: "/products" },
      { id: "add-product", label: "Add Product", href: "/products/add" },
      { id: "pending-products", label: "Pending", href: "/products/pending" },
      { id: "approved-products", label: "Approved", href: "/products/approved" },
      { id: "reported-products", label: "Reported", href: "/products/reported" },
    ],
  },
  {
    id: "categories",
    label: "Categories",
    icon: FolderTree,
    href: "/categories",
    submenu: [
      { id: "all-categories", label: "All Categories", href: "/categories" },
      { id: "add-category", label: "Add Category", href: "/categories/add" },
      { id: "sub-categories", label: "Sub Categories", href: "/categories/sub-categories" },
      { id: "sub-sub-categories", label: "Sub Sub Categories", href: "/categories/sub-categories/sub-sub-categories" },
    ],
  },
  {
    id: "trade-leads",
    label: "Trade Leads",
    icon: TrendingUp,
    href: "/trade-leads",
    submenu: [
      { id: "all-leads", label: "All Leads", href: "/trade-leads" },
      { id: "buy-leads", label: "Buy Leads", href: "/trade-leads/buy-leads" },
      { id: "sell-leads", label: "Sell Leads", href: "/trade-leads/sell-leads" },
    ],
  },
  {
    id: "payments-wallet",
    label: "Payments & Wallet",
    icon: Wallet,
    href: "/payments-wallet",
    submenu: [
      { id: "transactions", label: "Transactions", href: "/payments-wallet/transactions" },
      { id: "wallets", label: "Wallets", href: "/payments-wallet/wallets" },
      { id: "withdrawals", label: "Withdrawals", href: "/payments-wallet/withdrawals" },
      { id: "refunds", label: "Refunds", href: "/payments-wallet/refunds" },
    ],
  },
  {
    id: "investments",
    label: "Investments",
    icon: PiggyBank,
    href: "/investments",
    submenu: [
      { id: "all-investments", label: "All", href: "/investments" },
      { id: "active", label: "Active", href: "/investments/active" },
      { id: "completed", label: "Completed", href: "/investments/completed" },
    ],
  },
  {
    id: "consulting",
    label: "Consulting",
    icon: MessageSquare,
    href: "/consulting",
    submenu: [
      { id: "all-consulting", label: "All Consulting", href: "/consulting" },
      { id: "consultants", label: "Consultants", href: "/consulting/consultants" },
      { id: "sessions", label: "Sessions", href: "/consulting/sessions" },
      { id: "requests", label: "Requests", href: "/consulting/requests" },
    ],
  },
  {
    id: "content-ads",
    label: "Content & Ads",
    icon: Megaphone,
    href: "/content-ads",
    submenu: [
      { id: "banners", label: "Banners", href: "/content-ads/banners" },
      { id: "announcements", label: "Announcements", href: "/content-ads/announcements" },
      { id: "blogs", label: "Blogs", href: "/content-ads/blogs" },
      { id: "ads", label: "Advertisements", href: "/content-ads/ads" },
    ],
  },
  {
    id: "disputes",
    label: "Disputes",
    icon: AlertTriangle,
    href: "/disputes",
    submenu: [
      { id: "all-disputes", label: "All Disputes", href: "/disputes" },
      { id: "open", label: "Open", href: "/disputes/open" },
      { id: "resolved", label: "Resolved", href: "/disputes/resolved" },
      { id: "escalated", label: "Escalated", href: "/disputes/escalated" },
    ],
  },
  {
    id: "settings",
    label: "Settings",
    icon: Settings,
    href: "/settings",
    submenu: [
      { id: "general", label: "General", href: "/settings/general" },
      { id: "profile", label: "Profile", href: "/settings/profile" },
      { id: "roles", label: "Roles & Permissions", href: "/settings/roles-permissions" },
      { id: "email-templates", label: "Email Templates", href: "/settings/email-templates" },
      { id: "payment-gateways", label: "Payment Gateways", href: "/settings/payment-gateways" },
      { id: "system-logs", label: "System Logs", href: "/settings/system-logs" },
    ],
  },
];